apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-pod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: single-pod-app
  template:
    metadata:
      labels:
        app: single-pod-app
    spec:
      containers:
        - name: backend-container
          image: backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
        - name: envoy-container
          image: envoy-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
